import { generateText } from "ai";
import { createOpenAI } from "@ai-sdk/openai";
import type { LanguageModel } from "ai";
import { Ollama } from "ollama";
import { VercelBaseProvider } from "./vercel-base";
import type { ProviderType } from "../types/chat";

export class OllamaProvider extends VercelBaseProvider {
  readonly type: ProviderType = "ollama";
  readonly displayName = "Ollama";
  // Ollama's OpenAI-compatible endpoint does not accept item_reference message types
  // generated by the Vercel AI SDK's internal multi-step. Use the manual tool loop instead.
  protected readonly useManualToolLoop = true;

  protected createModel(): LanguageModel {
    const host = this.config.endpoint || "http://localhost:11434";
    return createOpenAI({
      baseURL: `${host}/v1`,
      apiKey: "ollama",
    })(this.config.model);
  }

  async listModels(): Promise<string[]> {
    try {
      const client = new Ollama({ host: this.config.endpoint || "http://localhost:11434" });
      const response = await client.list();
      return response.models.map((m) => m.name);
    } catch {
      return [];
    }
  }

  async testConnection(): Promise<boolean> {
    const client = new Ollama({ host: this.config.endpoint || "http://localhost:11434" });
    await client.list();
    return true;
  }
}
